services:
    db:
        image: postgres:18
        container_name: postgres-dev
        environment:
          POSTGRES_DB: notsys
          POSTGRES_USER: notuser
          POSTGRES_PASSWORD: notpass
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql

    keycloak:
        image: quay.io/keycloak/keycloak:26.8.0
        container_name: keycloak-dev
        command: start-dev
        environment:
          KC_BOOTSTRAP_ADMIN_USERNAME: admin
          KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        ports:
          - "8180:8080"
        volumes:
          - keycloak_data:/opt/keycloak/data

volumes:
  postgres_data:
  keycloak_data: