spring.application.name=notsys

management.endpoints.web.exposure.include=health

spring.datasource.url=jdbc:postgresql://localhost:5432/notsys
spring.datasource.username=notuser
spring.datasource.password=notpass

spring.jpa.hibernate.ddl-auto=validate
